import { chromium } from '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs';
const b = await chromium.launch(); const errs = [];
const p = await b.newPage({ viewport: { width: 1600, height: 1000 } });
p.on('pageerror', (e) => errs.push('P ' + e.message));
await p.goto('http://localhost:8791/'); await p.waitForTimeout(3500);
await p.screenshot({ path: '/tmp/n1.png' });
await p.evaluate(() => window.scrollTo(0, 900)); await p.waitForTimeout(300);
await p.screenshot({ path: '/tmp/n1b.png' });
await p.click('.row[data-id^="SEC"]'); await p.waitForTimeout(2500);
await p.screenshot({ path: '/tmp/n2.png' });
await p.click('[data-dtab="fin"]'); await p.waitForTimeout(2500);
await p.screenshot({ path: '/tmp/n3.png' });
await p.click('[data-dtab="flow"]'); await p.waitForTimeout(2500);
await p.screenshot({ path: '/tmp/n4.png' });
await p.click('[data-close-drawer]'); await p.waitForTimeout(400);
await p.click('.row[data-id^="DART"]'); await p.waitForTimeout(2500);
await p.click('[data-dtab="fin"]'); await p.waitForTimeout(2000);
await p.screenshot({ path: '/tmp/n5.png' });
await p.keyboard.press('Escape');
await p.click('#nav [data-go="popular"]'); await p.waitForTimeout(1500);
await p.screenshot({ path: '/tmp/n6.png' });
const m = await b.newPage({ viewport: { width: 390, height: 844 } });
m.on('pageerror', (e) => errs.push('M ' + e.message));
await m.goto('http://localhost:8791/'); await m.waitForTimeout(3000);
await m.screenshot({ path: '/tmp/m1.png' });
await m.evaluate(() => document.querySelector('.feed-wrap').scrollIntoView()); await m.waitForTimeout(300);
await m.screenshot({ path: '/tmp/m2.png' });
await m.click('.row[data-id^="SEC"]'); await m.waitForTimeout(2500);
await m.screenshot({ path: '/tmp/m3.png' });
console.log('ERR', errs); await b.close();
