import { chromium } from '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs';
const b = await chromium.launch();
const errs = [];
const p = await b.newPage({ viewport: { width: 1480, height: 1000 } });
p.on('pageerror', (e) => errs.push(e.message));
p.on('console', (m) => { if (m.type() === 'error' && !/Failed to load resource/.test(m.text())) errs.push(m.text()); });
await p.goto('http://localhost:8787/'); await p.waitForTimeout(2500);
await p.screenshot({ path: '/tmp/d1.png' });
await p.click('.row[data-id^="SEC-0000001"]'); await p.waitForTimeout(1200);
await p.screenshot({ path: '/tmp/d2.png' });
await p.keyboard.press('Escape'); await p.waitForTimeout(300);
await p.click('#flowTabs [data-tab="krInst"]'); await p.waitForTimeout(400);
await p.screenshot({ path: '/tmp/d3.png', clip: { x: 980, y: 300, width: 500, height: 700 } });
await p.click('.f-row[data-open]'); await p.waitForTimeout(1200);
await p.evaluate(() => document.querySelector('#drawer').scrollTo(0, 250));
await p.screenshot({ path: '/tmp/d4.png' });
await p.keyboard.press('Escape'); await p.waitForTimeout(2000);
await p.reload(); await p.waitForTimeout(2500);
console.log('popular chips', await p.locator('.pop').count());
const m = await b.newPage({ viewport: { width: 390, height: 844 } });
m.on('pageerror', (e) => errs.push('m:' + e.message));
await m.goto('http://localhost:8787/'); await m.waitForTimeout(2500);
await m.screenshot({ path: '/tmp/m1.png' });
await m.evaluate(() => document.querySelector('.feed-panel').scrollIntoView()); await m.waitForTimeout(300);
await m.screenshot({ path: '/tmp/m2.png' });
console.log('scrollW', await m.evaluate(() => document.documentElement.scrollWidth));
console.log('ERRORS', errs);
await b.close();
