import { chromium } from '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs';
const b = await chromium.launch(); const errs = [];
const p = await b.newPage({ viewport: { width: 1600, height: 1000 } });
p.on('pageerror', (e) => errs.push('P ' + e.message)); p.on('console', (m) => m.type() === 'error' && errs.push('C ' + m.text()));
await p.goto('http://localhost:8787/'); await p.waitForTimeout(3000);
await p.screenshot({ path: '/tmp/s1.png' });
await p.click('.row[data-id^="NEWS"]'); await p.waitForTimeout(2500);
await p.screenshot({ path: '/tmp/s2.png' });
await p.click('.row[data-id="DART-20260926800100"]'); await p.waitForTimeout(2500);
await p.click('[data-dtab="co"]'); await p.waitForTimeout(800);
await p.screenshot({ path: '/tmp/s3.png' });
await p.click('[data-dtab="doc"]'); await p.waitForTimeout(1500);
await p.screenshot({ path: '/tmp/s3b.png' });
await p.click('#themes li[data-theme="pos"]'); await p.waitForTimeout(400);
await p.screenshot({ path: '/tmp/s4.png', clip: { x: 0, y: 0, width: 1600, height: 700 } });
await p.click('.ai-promo button'); await p.waitForTimeout(1500);
await p.screenshot({ path: '/tmp/s5.png' });
await p.click('[data-close-modal]');
await p.fill('#search', '삼성'); await p.waitForTimeout(800);
await p.screenshot({ path: '/tmp/s6.png', clip: { x: 800, y: 0, width: 800, height: 500 } });
await p.click('#suggest [data-open-co]'); await p.waitForTimeout(2500);
await p.screenshot({ path: '/tmp/s7.png' });
await p.click('#moreBtn'); await p.click('#moreMenu [data-view="market"]'); await p.waitForTimeout(500);
await p.screenshot({ path: '/tmp/s8.png' });
await p.click('#btnUser'); await p.waitForTimeout(300);
await p.screenshot({ path: '/tmp/s9.png' });
const m = await b.newPage({ viewport: { width: 390, height: 844 } });
m.on('pageerror', (e) => errs.push('M ' + e.message));
await m.goto('http://localhost:8787/'); await m.waitForTimeout(2500);
await m.screenshot({ path: '/tmp/m1.png' });
await m.click('.row[data-id^="PR"]'); await m.waitForTimeout(2500);
await m.screenshot({ path: '/tmp/m2.png' });
console.log('ERR', errs); await b.close();
