import { chromium } from '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs';
const b = await chromium.launch(); const errs = [];
const p = await b.newPage({ viewport: { width: 1600, height: 1000 } });
p.on('pageerror', (e) => errs.push('P ' + e.message));
await p.goto('http://localhost:8791/'); await p.waitForTimeout(3500);
await p.screenshot({ path: '/tmp/o1.png' });
await p.evaluate(() => window.scrollTo(0, 500)); await p.waitForTimeout(200);
await p.click('.row[data-id^="PR"]'); await p.waitForTimeout(3000);
await p.screenshot({ path: '/tmp/o2.png', fullPage: false });
await p.evaluate(() => window.scrollTo(0, 800)); await p.waitForTimeout(300);
await p.screenshot({ path: '/tmp/o3.png' });
await p.goBack(); await p.waitForTimeout(800);
console.log('scrollY after back', await p.evaluate(() => [window.scrollY, location.hash, document.querySelector('#tabs .on').textContent]));
await p.click('#tabs [data-type="FILING"]'); await p.waitForTimeout(300);
await p.click('.row[data-id^="SEC"]'); await p.waitForTimeout(3000);
await p.screenshot({ path: '/tmp/o4.png' });
await p.click('[data-back]'); await p.waitForTimeout(800);
console.log('after back', await p.evaluate(() => [location.hash, document.querySelector('#tabs .on').textContent]));
const m = await b.newPage({ viewport: { width: 390, height: 844 } });
m.on('pageerror', (e) => errs.push('M ' + e.message));
await m.goto('http://localhost:8791/'); await m.waitForTimeout(3000);
await m.click('.row[data-id^="PR"]'); await m.waitForTimeout(3000);
await m.screenshot({ path: '/tmp/o5.png' });
console.log('ERR', errs); await b.close();
