import { chromium } from '/home/claude/.npm-global/lib/node_modules/playwright/index.mjs';
const b = await chromium.launch(); const errs = [];
const p = await b.newPage({ viewport: { width: 1500, height: 1000 } });
p.on('pageerror', (e) => errs.push('P ' + e.message));
await p.goto('http://localhost:8791/'); await p.waitForTimeout(4500);
await p.screenshot({ path: '/tmp/r1.png' });
await p.evaluate(() => (document.querySelector('.row[data-id^="SEC"]') || document.querySelector('.row')).click()); await p.waitForTimeout(4000);
await p.screenshot({ path: '/tmp/r2.png', fullPage: true });
await p.click('[data-ftab="ins"]'); await p.waitForTimeout(500);
await p.evaluate(() => document.querySelector('#aTabs').scrollIntoView()); await p.screenshot({ path: '/tmp/r3.png' });
await p.goto('http://localhost:8791/#home'); await p.waitForTimeout(2500);
await p.click('#tabs button[data-type="FILING"]'); await p.waitForTimeout(500); await p.evaluate(() => (document.querySelector('.row[data-id^="DART"]')).click()); await p.waitForTimeout(3500);
await p.click('[data-ftab="inv"]'); await p.waitForTimeout(500);
await p.evaluate(() => document.querySelector('#aTabs').scrollIntoView()); await p.screenshot({ path: '/tmp/r4.png' });
const m = await b.newPage({ viewport: { width: 390, height: 844 } });
m.on('pageerror', (e) => errs.push('M ' + e.message));
await m.goto('http://localhost:8791/'); await m.waitForTimeout(3500);
await m.evaluate(() => (document.querySelector('.row[data-id^="PR"]') || document.querySelector('.row')).click()); await m.waitForTimeout(3500);
await m.screenshot({ path: '/tmp/r5.png', fullPage: true });
console.log('ERR', errs); await b.close();
